### ISSUE TITLE
Mumble 1.3, TTS not functioning in OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by shadowbottle** [mumble-voip/mumble#1445]
Mumble-1.3.0~405~g3c280a6~snapshot
Sound files and notifications are working, but TTS messages are not being generated. I was looking for this feature and saw that it was supposed to be working in the snapshot so I decided to give it a try, but no dice. Not sure if this is deprecated/withheld for the moment or it's because I'm running Yosemite. I don't have any Mavericks machines to test on. The feature, of course, works fine when I'm booted into windows.

**Comment by shadowbottle** [comment]
Hrm, still not working here with snapshot 1.3.0~490~gb2f5bd0 on OS X Yosemite with a late 2013 MBP.

**Comment by beanoman4** [comment]
I had this problem in release 1.2.8, appears to be fixed for me on snapshot 1.3.0~540~gedd5509 on OS X 10.10 on a late 2014 Mac Mini

**Comment by mkrautz** [comment]
Thanks for the heads up.  I've backported this into the 1.2.x branch, and it should show up in 1.2.9.

**Comment by mkrautz** [comment]
Fixed in 1.2.9.

**Comment by shadowbottle** [comment]
OS X 10.11.4
Mumble snapshot  1.3.0~970~g888a459~snapshot

Mumble "allow apps to control your computer", still no working TTS. Has the fix been applied to the snapshots?

**Comment by shadowbottle** [comment]
Still broken. Is the fix from 1.2.9 going to make it's way into the 1.3 branch any time soon? Thanks!

**Comment by mkrautz** [comment]
1.3 already has the fix. It was backported from 1.3. Last I checked, TTS worked for me on both 1.2 and 1.3.

I'll try to look into this when I have some spare time.

I assume TTS works fine on your system otherwise? For example 'say' from a terminal. Have you tried a clean Mumble config? You should be able to temporarily move $HOME/Library/Preferences/net.sourceforge.Mumble.plist to another location, try Mumble, and move the config back when you're done testing.

**Comment by shadowbottle** [comment]
Ugh. Yeah, that seems to have done the trick. I'd tried this earlier without any success. I'll just start from fresh. Thanks for the suggestion, and yes, it appears to be working properly with a fresh profile.

**Comment by mkrautz** [comment]
Hmm. Odd. I wonder what broke it? Maybe your TTS was disabled in the "Configure" menu?

**Comment by shadowbottle** [comment]
Ok, so just to make sure I didn't miss that, lol, I did restore my old profile - it was, to my relief, still checked. I was immediately >_< as that absolutely seems like something I would overlook, but not so much. I did start out on a particularly early version of mumble for OS X, so at this point, I'm assuming corrupted plist. It's working now so, meh. Thanks for all the help though! Much appreciated (:

**Comment by zorgiepoo** [comment]
Just fyi, newer versions of macOS lazily reads/writes user defaults to plist files on disk and does as much possible in memory (for eg: performance reasons). So moving the plist files is not enough. You either have to kill all cfprefsd processes, reboot your Mac, or manipulate user defaults via the `defaults` tool.

**Comment by shadowbottle** [comment]
How new? El Cap or Sierra? Moving the plist/renaming it seemed to force the generation of a new one and used those settings instead so worked out in this case at least (El Cap).

**Comment by zorgiepoo** [comment]
New as in 10.9. It's not a reliable to just manipulate with the plist files.
