### ISSUE TITLE
AUDIO output device problems

### ISSUE THREAD

**Issue by LPCSparc** [mumble-voip/mumble#1573]
Okay so here is my exact problem, and I have pinpointed that it seems to specifically be Mumble (at fault) and Mumble only that I have this problem with. Here is the exact synopsis:

So my overall goal is live streaming while excluding audio from Mumble in the live stream. So I set up Mumble, VAC (virtual audio cable), Open Broadcaster Software, and a program to stream (specifically Guild Wars 2, MineCraft, Perfect World, Counter Strike, etc.). I set up VAC to have 2 virtual audio cables (at a minimum for the following purposes). I set Line 1 as the default device, I set Line 2 as the default communication device. I set Open Broadcaster Software to take audio (for the live stream) from Line 1, I set Mumble to output device = Line 2. Both Line 1 and Line 2 'repeat' to my actual speakers so I hear everything. With this exact set up I should be able to hear everything over my speakers, but Mumble should be excluded from the live stream. This however is not the case. I even re-installed TS3 (teamspeak 3) to test for desired functionality. With all programs set to use "default device" as input/output VAC, TS3, Open Broadcaster Software, and a game to stream it worked just fine. I didn't even have to change any input or output devices within all of the programs to get it to successfully exclude TS3 from the "live stream audio" segment.

So I figured okay, I will implicitly tell each and every program what input/output devices to use, instead of defaults. Seeing as I prefer Mumble over TS3 (former teamspeak veteran going back to TS1, until I found out about Mumble) I would much rather have to do this, that rely on "defaults". So again I set up Mumble to "output" to VAC "Line 2", a game to output to VAC "Line 1", and the audio input for Open Broadcaster Software to VAC "Line 1". Again, I could STILL hear Mumble in my live stream audio! Not to mention this would not be optimal as most games don't allow you to implicitly configure their sound output device. Luckily, at least for testing purposes, Guild Wars 2 does! Though as I mentioned, implicitly setting output/input devices on all these programs still failed, I could still hear the Mumble audio in the live stream audio feed. So I again tested with TS3, setting TS3 output as VAC "Line 2", GW2 to output VAC "Line 1", and OBS audio input as VAC "Line 1". Again, the audio from TS3 successfully did not play in my live stream audio feed, and only over my speakers as desired.

So then I decided to attempt further testing on Mumble since Mumble already seemed to be the direct culprit of not being able to obtain the desired results. I left the output setting in Mumble to VAC "Line 2" but changed the default device and default communication device to "Line 3" (a VAC line NOT in use, and NOT re-routed to my speakers). Sure as ***\* when I did this Mumble was no longer in the live stream audio, AND could not longer be heard over the speakers. So in my tests, even though the Mumble audio output device was set to "Line 2" but I changed the "default device" settings in Win7 to "Line 3", Mumble started outputting to Line 3 _anyways_. I then changed the "default communication device" (in Win7) to "Line 2", still no audio in speakers or live stream feed. I then changed the "default device" (in Win7) to "Line 2" and Mumble audio was restored; in _both_ my speakers and the live stream feed.

So it would seem to me that Mumble is not respecting the audio output device settings. It seems to fail to respect the "default communication device" settings of Win7, and seems to only send output to whatever device is listed as the "default" device in Win7 despite whatever else may be set in Mumble itself.

Which at the same time, I must admit, is VERY odd seeing as I have previously successfully set up a "music bot" and even a "TS patch" in Mumble previously. The music bot I can sort of understand since that's merely changing the input device, and I haven't noticed a problem with Mumble not respecting the input device settings. The music bot is very straight forward. Using VAC, a media player, and mumble: set a media players output to a VAC Line 1, set the input device for Mumble to VAC Line 1 (and open mic) - presto, music bot. Though I have also succeeded in setting up even a two way TS patch (because my guild uses Mumble, but we still wanted to be able to communicate with people on the game server that used TS). For that I would set up Mumble as TS "side by side", Set TS input to Line 1, TS output to Line 2 - Mumble input to Line 2, Mumble output to Line 1. Presto, I had an instant two way TS/Mumble "patch" - tested and fully working. People in the same channel could talk to each other just fine regardless of whether they were on TS or Mumble!

So, this is all REALLY boggling to me! Why would Mumble respect output settings in the instance when I made that Mumble => TS => Mumble "patch", but not when I'm trying to set up a live stream, and exclude the audio from Mumble from said stream?

**Comment by LPCSparc** [comment]
Nobody?

**Comment by mkrautz** [comment]
Thanks for the detailed report.  Unfortunately, I don't think any of us have had the time to look into this yet!

Definitely sounds like a bug, though.

**Comment by LPCSparc** [comment]
Okay, I did at least want to confirm it's been read / now known about.

It does seem really odd, which is why I tried to give as much detail as possible. Especially since it seems to respect the output settings when I was doing one thing, but then didn't when I'm doing something else.

If any further information is required be sure to let me know!

**Comment by hacst** [comment]
Strange. With two real audio devices I can't reproduce this issue (Windows 8.1 pro here). Mumble correctly keeps track of default and default communications device no matter how much I switch them around. Audio is only ever played to the current default communications device. Same with selecting a fixed output device and changing the defaults.

This might be an issue specifically connected to virtual audio cable. Could you upload/paste your "Console.txt" from %APPDATA%/Mumble somewhere? Probably best to delete it beforehand and the reproduce the issue(s). Otherwise it'll be quite big if you use mumble a lot. We do log information on the audio devices we select there which might give us a hint on what is going on here. Maybe it's something straight-forward.

Unfortunately I currently don't have the time to read up on virtual audio cable to try to reproduce this myself.

**Comment by gibbed** [comment]
Virtual Audio Cable doesn't support IEEE floating point formats, as mentioned in the official documentation ("Almost any of fixed point PCM audio formats (1000..1000000 samples per second, 8..32 bits per sample, 1..8 channels). Floating point formats are not supported.").

Mumble will silently fail (outputs to Console.log with "WASAPIOutput: Subformat is not IEEE Float: hr=0x00000000") if you select a VAC Line as your output device with WASAPI as your system selection (only choice on Windows 8.1 for me).

I patched Mumble to remove the floating point checks and Mumble is now able to output to a Virtual Audio Cable line with no issues for me.

(Specifically, https://github.com/mumble-voip/mumble/blob/master/src/mumble/WASAPI.cpp#L872)

**Comment by hacst** [comment]
@LPCSparc The new snapshot 1.3.0-547 has a patch that should resolve your issues with VAC. Could you please verify it is working for you? Thanks.

**Comment by hacst** [comment]
I'll assume this is resolved. If it turns out it isn't we'll reopen it.

**Comment by r-pufky** [comment]
I just confirmed that this issue still happens, on mumble 1.2.10, windows 10 pro. (issue not resolve).

Exact same problem -- mumble only outputs to the 'default device' set in sound playback, and not what is specified in the mumble configuration.

Please let me know if you need more info, or if you want me to do any additional reporting.

**Comment by r-pufky** [comment]
I've also confirmed this still exists in the latest stable version: 1.2.17

**Comment by mkrautz** [comment]
@r-pufky But is it fixed in 1.3.x? That's where the fix landed.

**Comment by mkrautz** [comment]
Hm. I guess not, since (I believe) the float fixes were backported to 1.2.x.

**Comment by mkrautz** [comment]
Anyway, still interested in whether 1.3.x is affected. Thanks! :-)

**Comment by r-pufky** [comment]
@mkrautz  Confirmed that latest build from mumble page is affected as well: 1.3.0~1703~gf47df77

**Comment by mkrautz** [comment]
@r-pufky Could you please jot down some reproducible steps for me? I'm failing to reproduce the issue.
Mumble is set to use the default device, and when I switch the default communication device for playback or recording, Mumble does the right thing.

Thanks!

**Comment by r-pufky** [comment]
Test C ('Tricking' the correct behavior):
1. Set default device to toslink
2. Start any game / recording software / mumble
3. Set default device to headset earphone
4. Open Windows Playback devices / OBS -- audio streams are now correctly separated to both devices (game to toslink, mumble to headset earphone). Verify with game audio equalizer on toslink and mumble text-to-chat on headset earpiece.
5. This works until the game is restarted, then you have to run through all these steps to setup again.

**Comment by mkrautz** [comment]
Oh, so ALL your issues are related to Text-to-Speech, @r-pufky?

**Comment by r-pufky** [comment]
I've just re-ran these tests, and it seems that you are correct, this *only* is currently happening with text to speech. (all versions).

My assumption is that setting audio output sets all audio output for mumble, including text-to-speech.

**Comment by mkrautz** [comment]
Unfortunately, that's not the case. We use SAPI 5.2 on Windows for Text-to-Speech, and the very simply part of the API we're using (a single method) doesn't allow us to set a target device -- the default sound device is always used.

It seems like it is possible, with some amount of work, to fix this issue. But it's worth noting that this isn't a regression -- it has existed in Mumble for probably 10 years, or whenever Mumble got Text-to-Speech suport. :-)

Anyway, I'll create a new issue to track this problem.

Thanks for reporting it.

**Comment by mkrautz** [comment]
New issue is at https://github.com/mumble-voip/mumble/issues/2667
