### ISSUE TITLE
Unable to move users in Mumble

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1610]
Server is running Linux Murmur snapshot 540.

User on Mumble snapshot 540 is able to click and drag people to Move them to channels (His permissions are correct) yet Admins are unable to move users.

I was able to confirm this by testing it on my laptop.

Reverted my Mumble snapshot (been using 532) and was able to move users like before.

Edit: This issue is also in snapshot 564.

**Comment by nicolasjoly** [comment]
Oh! That's why some of my friends are intermittently unable to move people. I'm full admin (Write ACL) on everything and don't seem to be having this problem. But I did get some reports of unable to move (they should be able).

**Comment by Tarun80** [comment]
Full admin here too and unable to move anyone. Doubt it's a permission problem since a rollback of the snapshot fixed it.

**Comment by synapse84** [comment]
Issue appeared between 549 and 564.

| Version       |  |
| ------------- | -----|
|547 | can move
|547 x64 | can move
|549 | can move
|549 x64 | can move
|564 | can't move
|564 x64 | can't move
|567 | can't move
|567 x64 | can't move

Running build 566 on Linux and I'm able to move without an issue.

**Comment by hacst** [comment]
Thanks for all the information. I asked @mkrautz and he said it is likely Qt 5.4 1/5.4.0 related. We'll look into it.

**Comment by Tarun80** [comment]
Issue persists with build 570.

**Comment by hacst** [comment]
If you are seeing what I'm seeing you can still move them. However it's horribly fiddly. You have to select and focus the user first and then start dragging them. Obviously still have to fix this.

**Comment by Tarun80** [comment]
On my laptop where I'm running snapshots I've tried this with no success at all. I'll click the user, they will be highlighted, and I get the no symbol and cannot drag them to any channel.

**Comment by synapse84** [comment]
On Linux I was able to reproduce this bug on the same mumble snapshot version simply by compiling with Qt 5.

https://www.youtube.com/watch?v=kQ00HVExopk

This issue is very likely related to the bug hacst linked to. Which has an upcoming fix in the Qt codereview https://codereview.qt-project.org/#/c/110724/.

**Comment by Tarun80** [comment]
Looks like this was fixed in Qt 5.4.2 as of May 1, 2015. That should hopefully fix this issue. Now for 5.4.2 to release.

**Comment by Tarun80** [comment]
Resolved in build 3d4663465ea1e528a299f1939237c31a4188775.

**Comment by Prior99** [comment]
I am experiencing this issue again since yesterday. Mumble `1.3.0~2424~gd66eeeb~snapshot`. Qt `5.9.0` on Arch Linux.

**Comment by synapse84** [comment]
Can confirm this issue is back with Qt 5.9.0.

Snapshot 2424 with Qt 5.8.0 allowed me to move users. I then upgraded Qt to 5.9.0 and could no longer move users.

**Comment by Prior99** [comment]
@Tarun80 this issue should probably be reopened?

**Comment by mkrautz** [comment]
I just built Qt from the dev branch to submit a fix for https://github.com/mumble-voip/mumble/issues/3124

I'll take a look at this while I work on that.

**Comment by JuniorJPDJ** [comment]
Confirming, also not working when compiling at arch linux with mumble-snapshot aur package.
Latest stable version of everything installed.

**Comment by synapse84** [comment]
@Prior99 @JuniorJPDJ
qt5-base on arch was updated to 5.9.1 a few days ago, and I just updated the mumble-snapshot aur package to the latest snapshot (2458). After updating, I was able to move users, so it should now be resolved.

**Comment by edm7707** [comment]
I think this issue can be closed?
