### ISSUE TITLE
Mumble visually disappears after locking and unlocking/logging back into Ubuntu

### ISSUE THREAD

**Issue by mikesulsenti** [mumble-voip/mumble#1679]
I noticed this after locking my system once and going to sleep. I think this only happens in more extended period of lock. When the system is unlocked later, mumble is no longer visibly there. I can can still use my push to talk key to talk to people and they can talk to me and if they send messages it shows up in the notifications.

To fix this I have to kill the process and restart mumble.

![screenshot from 2015-05-24 14 25 21](https://cloud.githubusercontent.com/assets/8174608/7789057/3a2f0960-0221-11e5-85b1-f5bf9696b138.png)

The same thing happens to Steam too.

Mumble version is on 1.3.0~628~gfcb908b~snapshot-1~ppa1~trusty1
Ubuntu 14.04.2

**Comment by Nephyrin** [comment]
I have noticed this on Arch+KDE as well. Occasionally the system tray icon simply vanishes, and thus once mumble is minimized its minimize-to-tray functionality renders it completely inaccessible.

Invoking `mumble` again is supposed to focus the existing session, but in this state it has no effect. Mumble refuses to show itself, and must be hunted down with a pkill :-/

Incoming and outgoing voice + PTT continues to work in this state, however.

**Comment by Nephyrin** [comment]
Update: After about 10 seconds of fiddling I can reproduce this in KDE, and I suspect any other WM where you can piecemeal restart the system tray app.

- With mumble visible, kill and restart `plasma-desktop`, which is responsible for the system tray
- When it comes back up, every system tray icon *except* mumble will remain
- Minimize mumble

Mumble is now running, but its UI entirely inaccessible, even by running `mumble` in a terminal.

**Comment by mkrautz** [comment]
Thanks for confirming that it is an issue on other desktop environments. My initial hunch was that it was an app-indicator issue with Ubuntu/Unity and Qt 5.

I will look into this!

**Comment by Frogging101** [comment]
Can confirm that Mumble disappears completely (window and tray icon) when the X display is lost (such as if you turn off your monitor). This didn't happen on 1.2.12. It only started happening when I updated to the snapshot. I think it is likely a result of [this Qt5 bug](https://bugreports.qt.io/browse/QTBUG-42985), fixed in Qt 5.6.

I can confirm also that restarting plasma-desktop will cause Mumble's tray icon to go away forever. That was an issue in 1.2.x as well, however.

**Comment by haasn** [comment]
Mumble also disappears if you switch workspaces in xmonad and back again. Not sure if it's the same issue, but it seems similar.

**Comment by AdamNiederer** [comment]
This happens in Openbox as well. Switching virtual desktops will make the main window disappear.

The server selection window is unaffected, strangely.

**Comment by staticfox** [comment]
Same issue

System specs:
```
OS: Arch Linux 
Kernel: x86_64 Linux 4.8.10-1-ARCH
Shell: bash 4.4.5
WM: OpenBox
```

Mumble git rev:
`2a106e19c7`

**Comment by tidux** [comment]
On Arch+Fluxbox, the tray icon continues to work but the main window is lost without a full reset.

**Comment by qsuscs** [comment]
I have the same issue as @haasn in XMonad, and the `#xmonad` IRC channel helped me investigate a bit:
```
23:43 <qsx> i have strange problems with mumble
23:43 <qsx> when i switch workspaces, it completely disappears
23:43 <qsx> it used to show up again upon clicking its icon in the systray, or by running /usr/bin/mumble again, but now its window flickers briefly and then disappears again
23:44 <qsx> so i have no possibility to get mumble’s window again once i switched workspaces
23:48 <geekosaur> qsx, do you have something in the ManageHook for it? window show/hide can be done in several ways, the most obvious of which will send it through the ManageHook again
23:49 <qsx> geekosaur: i just did (className =? "Mumble" --> doFloat), but it changed nothing
23:49 <geekosaur> and I have seen programs get confused by this if they try to save window/workspace settings, especialluy since xmonad's workspace model is not EWMH's which will confuse some EWMH using programs
23:52 <geekosaur> qsx, can you run 'xlsclients -l' and send the output to http://lpaste.net ?
23:54 <qsx> geekosaur: i hope you accept this too … https://paste.pound-python.org/show/y7YsetfS0zlt0urdh0d4/
23:55 <geekosaur> about the only one I don't deal with is pastebin.com with its damned ads
23:55 <qsx> agreed
23:55 <geekosaur> hm, well that was less than useful --- manpage implies it should have more hints included :/
23:56 <geekosaur> xwininfo -id 0x2800016
23:56 <qsx> https://paste.pound-python.org/show/3SgrBLaFIFT1qTEVP7lb/
23:57 <geekosaur> siiigh
23:57 <geekosaur> ok, mumble has become confused and is unmapping itself for some reason
00:01 <geekosaur> so, I think you have to `killall mumble` and rerun it if that doesn;t work then it's remembering its state somewhere and that needs to be purged... which might also kill the rest of its configuration :/
00:02 <qsx> i can quit it (via trayicon), but then i obviously quit the connection, leave the channel, …
00:04 <geekosaur> that may be your only option though. it's confused itself, xmonad can't force it to not unmap itself
00:28 <qsx> O_o
00:33 <dmwit> You should also definitely complain to the mumble folks.
```
The two pastes copied here:
```
$ xlsclients -l
Window 0x800001:
  Machine:  coruscant
  Name:  NetworkManager Applet
  Icon Name:  nm-applet
  Command:  nm-applet
  Instance/Class:  nm-applet/Nm-applet
Window 0xe00001:
  Machine:  coruscant
  Name:  blueman-applet
  Icon Name:  blueman-applet
  Command:  blueman-applet
  Instance/Class:  blueman-applet/
Window 0x1c00001:
  Machine:  coruscant
  Name:  Terminal
  Icon Name:  Terminal
  Command:  gnome-terminal-server
  Instance/Class:  gnome-terminal-server/Gnome-terminal-server
Window 0x2800016:
  Machine:  coruscant
  Name:  Mumble -- Compiled by User
  Command:  mumble
  Instance/Class:  mumble/Mumble
Window 0xc00001:
  Machine:  coruscant
  Name:  taffybar-linux-x86_64
  Icon Name:  taffybar-linux-x86_64
  Command:  taffybar-linux-x86_64
  Instance/Class:  taffybar-linux-x86_64/Taffybar-linux-x86_64
Window 0x1a00001:
  Machine:  coruscant
  Name:  google-chrome-stable
  Icon Name:  google-chrome-stable
  Command:  google-chrome-stable
  Instance/Class:  google-chrome-stable/Google-chrome-stable
Window 0x2200001:
  Machine:  coruscant
  Name:  profanity
  Icon Name:  profanity
  Command:  profanity
  Instance/Class:  profanity/Profanity
Window 0x2600001:
  Machine:  coruscant
  Name:  profanity
  Icon Name:  profanity
  Command:  profanity
  Instance/Class:  profanity/Profanity
```
```
$ xwininfo -id 0x2800016

xwininfo: Window id: 0x2800016 "Mumble -- Compiled by User"

  Absolute upper-left X:  654
  Absolute upper-left Y:  223
  Relative upper-left X:  654
  Relative upper-left Y:  223
  Width: 1260
  Height: 853
  Depth: 24
  Visual: 0x61
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x60 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +654+223  -646+223  -646-364  +654-364
  -geometry 1260x853+654+223
```
This is from version `1.2.5-1828-g9e26faee`.

**Comment by mkrautz** [comment]
@qsuscs @haasn 
Fixed in https://github.com/mumble-voip/mumble/pull/3025

But I'm not sure what that version of Mumble is... 1.2.5-18228-g9e26faee? That seems like 1.3.0, not 1.2.5.

**Comment by qsuscs** [comment]
It’s the output from https://git-scm.com/docs/git-describe, so therefore also a version string git can parse.  Read it like “Tag 1.2.5, with 1828 commits on top leading to exact commit `9e26faee`”.  A combination of unambiguity for machine parsing and sensible for humans to read.

Thanks for fixing.

**Comment by mkrautz** [comment]
Ah, I knew it was the output of 'git describe', but I didn't put the pieces together.

At some point, we switched from 'git describe' to our own notifation, based on the 'git describe' format, but more sensible for mere mortals. So, our naming for that version is 1.3.0~1828~g9e26faee.

I thought it was a distro package or something. :-)

**Comment by Kissaki** [comment]
@mkrautz Is this fixed by #3025, which landed?

**Comment by mkrautz** [comment]
There are various issues here:

- Mumble doesn't work with the X display disappears. (Not fixed by us, probably fixed by Qt 5.6+)
- Mumble doesn't behave correctly in WMs that don't have a default system tray, such as Openbox or XMonad. (Fixed)
- Mumble's tray icon disappears when the Plasma shell is killed. (Not fixed by us, but it doesn't happen anymore.)
- Tray icon works on Fluxbox, but the main window is lost without a full rest. (Can't reproduce).
- Drybone's report, which is that, on Ubuntu, logging out/locking the screen and sleeping causes Mumble to disappear. (Can't reproduce.)

**Comment by AdamNiederer** [comment]
Confirming that #3025 fixed the issue for me (bullet # 2 above). Thanks, guys!

**Comment by flussence** [comment]
What seems to be happening here is that the "Hide in tray on minimise" option is actually trayifying Mumble on any UnmapNotify event. This includes switching desktops, toggling window shade state, and I guess the Ubuntu lockscreen thing similarly hides windows for security reasons.

To fix it the code needs to test for `_NET_WM_STATE = _NET_WM_STATE_HIDDEN`, it's only set when the window is minimised.

**Comment by aphirst** [comment]
I can confirm that the issue still occurs for me when changing workspaces with OpenBox.

**Comment by AlainKnaff** [comment]
I can confirm that the issue still occurs for me when changing workspaces with KDE .
It's the version included by default in Debian 10: 1.3.0~git20190125.440b173+dfsg-2

**Comment by ZeroAbility** [comment]
Check if this is a duplicate of https://github.com/mumble-voip/mumble/issues/1233

Also, Ubuntu 14.04 is end of life.

**Comment by Krzmbrzl** [comment]
This issue seems to be an involuntary collection of multiple things. It is unclear to me what parts of this may be fixed already and which may be unresolved. If you are still affected by any of the mentioned bugs, please let us know and we either find an appropriate issue that tracks this or we create a dedicated issue for that specific problem.
