### ISSUE TITLE
Muting self in client creates multiple .png duplicates in temp folder

### ISSUE THREAD

**Issue by artvindaloo** [mumble-voip/mumble#1854]
In Windows 10, muting or deafening yourself creates duplicate copies of a 6kb PNG image (a blue circle with a white 'i' in the middle) in Appdata\Local\Temp - these are not removed and build up over time.

**Comment by mkrautz** [comment]
@artvindaloo Which version of Mumble are you seeing this on?

**Comment by artvindaloo** [comment]
It's version 1.2.10 - I know several other people with same version on Windows 10 with the same issue

**Comment by Rantanen** [comment]
This seems to happen also whenever users leave/join channels.

Maybe related to the code that is supposed to show the notification message at the bottom right of the screen? Can't see that message anywhere in Win10 anymore.

**Comment by Rantanen** [comment]
Confirmed. Disabled the notifications on all messages in the mumble settings and the temp files are no longer created.

**Comment by mkrautz** [comment]
I'm thinking this has been fixed by Microsoft by now, but I haven't had time to test it.

Assigning myself...

**Comment by Rantanen** [comment]
Just updated to the latest Snapshot. Still reproducible to some extent.

- Enabled notification for self mute/deafen.
- Self muted/deafened and received notification in Windows notification area.
- Observed new png file in the temp location.
- The png was removed when the notifications disappeared from bottom right.
- Self muted/deafened several times in a row without giving time for the notifications to disappear.
- Observed several png files in the temp location.
- Latest png file was removed when the notifications disappeared from bottom right.

So it seems that opening a new notification before the old one has disappeared clutters the temp directory.

**Comment by Rantanen** [comment]
Aaaand... while I was typing that response, something cleaned all the temp files away.

**Comment by mkrautz** [comment]
The behavior I see with the current Windows 10 Anniversary Update build is totally fine.

One PNG is stored in total. Once a new notification is shown, the old PNG is deleted.
When the notification finally disappears, so does the PNG, after a short while.

Closing this, as it was a Windows bug all along. :-)
