### ISSUE TITLE
New Snapshot 1.3.0~2306~g46462cd~snapshot affects game negatively

### ISSUE THREAD

**Issue by jammet** [mumble-voip/mumble#3029]
New Problem in Snapshot 1.3.0~2306\~g46462cd\~snapshot 

Most likely involving the overlay.

After installing this update patch, it's started to affect a game I play.

I cannot MOVE anymore in DayZ now. It is like every time I press a key on the keyboard, the game stutters and lags and audio drops out entirely. It acts as if I was pressing every key on the keyboard at the same time.

This did not happen at all with the previous patch! And I can stop this behaviour by quitting mumble, OR disabling the overlay! But I need Mumble in my DayZ. ;) If possible with the overlay.

---

* Reported for DayZ and Planetside 2
* BattleEye Anticheat was suggested as possible culprit
* Stuttering upon keyboard key presses

https://www.battleye.com/support/faq/
> My BE Launcher is stuck at “Starting BattlEye Service…” stopping my game from launching. What’s wrong?
> 
> Something on your system prevents the BE Service from functioning properly. Please check the FAQ entry regarding BE Service installation/startup failures above for solutions.

**Comment by davidebeatrici** [comment]
Is the overlay enabled? If yes, try to disable it.

**Comment by jammet** [comment]
I just did, the overlay is causing this in some way. ;(

**Comment by davidebeatrici** [comment]
Is the overlay showing up in the game if you enable it?

**Comment by jammet** [comment]
I will restart the PC, game and mumble a few times. So far it does not.

**Comment by jammet** [comment]
It shows up in Final Fantasy X HD Remaster. Not in Torchlight 2. Not in DayZ.

**Comment by mkrautz** [comment]
@jammet Is this a regression? Which version worked fine, which version is broken?
We haven't made any big changes to the overlay code itself that should trigger this behavior.

**Comment by jammet** [comment]
I wish I could give you more precise information, but all I could tell you
is, that one automatically detected patch download earlier, this was not
happening.

Whatever this is, it affects only the keyboard of all input devices. So I
can can turn with the mouse without issue, but as soon as one or more
keyboard keys are pressed, this game will act like I press a great number
of them, stressed out.

Maybe something was changed about how keystrokes for Mumble are detected
recently? Not that I understand why this is happening when of all things
the overlay is enabled.

Sorry about this lack of useful information.

**Comment by mkrautz** [comment]
Can you try to navigate to Configure -> Settings -> Shortcuts and disable `Enable Windows hooks` and see if that helps?

**Comment by jammet** [comment]
Yes, of course. I've tried this a moment ago, also went through the other
two options (like Xinput) in that section, restarted Mumble, launched DayZ
this time with the Overlay re-enabled.

The problem persists. I wish this would have been an easy solution, but it
seems to be something that's not immediately obvious somehow. I am glad
that I can make this work at all, of course having the overlay would be
very nice. Does anyody else own that game and has that exact same issue?

**Comment by jammet** [comment]
During our first group play (with a few players not present) yesterday, One
other player reliably reproduced the same problem I'm encountering, and on
other has not.

We don't live near each other, so we don't know how to compare details of
our systems. For starters, we both use Windows 10 right now. That probably
does not help much. ;(

**Comment by Remadan** [comment]
I have the same issue in Planetside 2. I'm sure it has something to do with BattlEye Anti-Cheat. There is a mentioning of similar problems in BattlEye FAQ: https://www.battleye.com/support/faq/. The only fix i found currently is to restart BattlEye service after game have already started.

**Comment by mkrautz** [comment]
@jammet Just to confirm, it only happens in DayZ for you?

**Comment by mkrautz** [comment]
Also, it seems like DayZ uses BattlEye (from a quick Google search). And the symptoms linked to by @Remadan seems to fit the problem... Hmm...

The FAQ entry says "[...] constantly reloading into your game [...]". Mumble should, AFAIK, only try to inject once.

Did this problem with BattlEye only happen recently?
I changed the overlay to unload itself when it is unsuccessful. I'm not sure if that has anything to do with it....: 

https://github.com/mumble-voip/mumble/commit/2f07778a0eaf349b6a80489007ac31b7e54064f2

**Comment by Remadan** [comment]
@mkrautz I updated from 1931 to 2306 snapshot around 17 of april. Problem appeared the same day. Since mumble is the only thing that changed that day (no ingame patch), it was easy to find a culprit.

**Comment by jammet** [comment]
Yes - SO FAR this only happens in DayZ, but I can try other games if you like. I'm not sure if I have any others that use BattlEye, but I could try and check.

**Comment by jammet** [comment]
I've looked up that H1Z1 King of the Kill uses BattlEye.

**Comment by mkrautz** [comment]
Hopefully fixed in https://github.com/mumble-voip/mumble/commit/8f65051faf9e1cb4a921c4512387ddfc35eae9e5.

Building a new snapshot as we speak...

**Comment by Remadan** [comment]
Tried out new snapshot. Stuttering is gone. Overlay still not showing though.

**Comment by mkrautz** [comment]
@Remadan And, your test case is Planetside 2?

**Comment by Remadan** [comment]
@mkrautz Yes, it is Planetside 2.

**Comment by Remadan** [comment]
@mkrautz I downloaded 1937 snapshot  again and overlay is showing fine in planetside.

**Comment by mkrautz** [comment]
Do you use PlanetSide 2 via Steam, or standalone?

**Comment by mkrautz** [comment]
If it's standalone, we'd need to add the PlanetSide 2 launcher (or executable) to the launcher/program whitelist.

**Comment by Remadan** [comment]
@mkrautz It is standalone. I have added **LaunchPad.exe** to _Allowed launchers_ list and overlay is showing again. I think the same launcher name used in most of daybreak games.

**Comment by jammet** [comment]
Most of the time the Overlay is not showing up in DayZ anymore. In this and the previous release, not once. But the stuttering issue has been taken care of, and I am very glad. 

Sadly, DayZ does not have a launcher of sorts, so this problem with the Overlay not being visible, is probably related to something else. I don't know?

**Comment by Kissaki** [comment]
Added a summary to the first post:


* Reported for DayZ and Planetside 2
* BattleEye Anticheat was suggested as possible culprit
* Stuttering upon keyboard key presses

https://www.battleye.com/support/faq/
> My BE Launcher is stuck at “Starting BattlEye Service…” stopping my game from launching. What’s wrong?
> 
> Something on your system prevents the BE Service from functioning properly. Please check the FAQ entry regarding BE Service installation/startup failures above for solutions.

We should check the debug/trace logs.

**Comment by mkrautz** [comment]
@Kissaki I believe the stuttering is fixed via https://github.com/mumble-voip/mumble/commit/557eacd1e7e829c4a4e7af04b97d7ffdeed5471e.

**Comment by Kissaki** [comment]
Download and start [DebugView](https://technet.microsoft.com/en-us/sysinternals/bb896647.aspx).
Then create a file named `debugoverlay` (no file name extension) next to your game exe.

Then launch the game, wait a moment, press a key, see if the log messages change, and post them here?

I don't own DayZ, but I could install Planetside 2.

Actually, I still have Planetside 2 installed it seems. I’ll have a look.

**Comment by Kissaki** [comment]
I was able to run it on PS2. Did not experience any stuttering upon keypresses.

@jammet @Remadan can you confirm this is no longer an issue for you?

Closing this as solved. Please give notice if the issue still exists.
