### ISSUE TITLE
Symbol lookup error when trying to launch overlay:  undefined symbol: glPopClientAttrib

### ISSUE THREAD

**Issue by Lurkki14** [mumble-voip/mumble#3542]
I'm getting an error where launching Xonotic with the overlay gives an error: 
>$ LD_PRELOAD=./libmumble.so xonotic-glx
xonotic-glx: symbol lookup error: ./libmumble.so: undefined symbol:  glPopClientAttrib

but the overlay appears on glxgears just fine. Xonotic is an LSB executable whereas glxgears is an LSB shared object so could it be related to that?

**Comment by davidebeatrici** [comment]
Successfully reproduced.

**Comment by davidebeatrici** [comment]
Fixed in the (W.I.P.) CMake project with:
```cmake
if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
	target_link_options(overlay_gl_x64 PRIVATE "-Wl,-z,lazy")
	target_link_options(overlay_gl_x86 PRIVATE "-Wl,-z,lazy")
endif()
```

Those options were added to the qmake project in 859da4dabec070959b5c06f8d32512990d7ec9c2.

**Comment by svenstaro** [comment]
This is still happening for us: https://bugs.archlinux.org/task/66534

**Comment by Krzmbrzl** [comment]
See e.g. #5852
