### ISSUE TITLE
Mumble asks for permissions to access every application that opens (not working)

### ISSUE THREAD

**Issue by jmachuca77** [mumble-voip/mumble#3552]
When mumble is open and other applications are in use, OSX sends a warning that mumble is trying to access the applications data and prompts to allow access. These are two examples of the prompts:

![screen shot 2018-11-26 at 8 39 37 am](https://user-images.githubusercontent.com/1664405/49025587-3e099980-f159-11e8-9d75-2e44a89e53b0.png)
![screen shot 2018-11-26 at 8 39 37 am](https://user-images.githubusercontent.com/1664405/49025592-3fd35d00-f159-11e8-9ca1-861d250816f3.png)

**Comment by thejohnha** [comment]
I have this issue too - anyone know why it happens? Running mojave 10.14.4

**Comment by markx2** [comment]
I have this issue too, latest Mumble, a;so Mojave 10.14.4

![coda2](https://user-images.githubusercontent.com/7057656/56089180-18222e80-5e87-11e9-94ef-9888c31271f6.png)


<img width="217" alt="minecraft" src="https://user-images.githubusercontent.com/7057656/56089183-1ce6e280-5e87-11e9-824e-4fc47c90731c.png">


There is no way at all I would install this on a Windows machine because of the above.

Issue opened November 2018, **issue still being ignored  April 2019**

**Comment by bendem** [comment]
My guess is, it's the overlay/plugins that's asking permission too aggressively. You can try and disable it/them in the preferences and see if it still asks for those permissions.

**Comment by reelsense** [comment]
Isn't this what causes it?

<img width="665" alt="Security___Privacy" src="https://user-images.githubusercontent.com/5644977/58363085-df954d80-7e53-11e9-8e26-c8275a0eb91f.png">

**Comment by dblanch369** [comment]
Adding Mumble to the Accessibility should fix that error, yes.  There are a number of issues with Mumble running on 10.14, that one above is just one of them.

**Comment by wolflarson** [comment]
This is still an issue on macOS 10.15 public betas. Having mumble in "Accessibility" does not resolve the issue.

Mumble overlay is not installed
![Screen Shot 2019-07-14 at 2 10 04 PM](https://user-images.githubusercontent.com/16849308/61187583-31cb4180-a641-11e9-80d9-cd981960fda1.png)

**Comment by iammeat** [comment]
A much greater problem for me on Mojave 10.14.6.  Removing Mumble from the Accessibility list causes my entire machine to lock up, requiring a hard reboot.

**Comment by davidebeatrici** [comment]
When Mumble is running?

**Comment by iammeat** [comment]
Yes, it was running at the time.

**Comment by jmachuca77** [comment]
This is not an issue with overlay, I don't have overlay installed or enabled. Furthermore the issue is a security risk, as mumble asks for access to applications that contain sensitive information that it has no reason to access at all.

**Comment by globeFrEak** [comment]
Any solution for this bug on macOS Catalina?

**Comment by Krzmbrzl** [comment]
I think this is because the overlay is loaded even if it is disabled...

**Comment by migaspar** [comment]
is it going to be fixed soon please? due to corona we'd like to use mumble in our company, but i as the admin can't expect our colleagues to deal with this bug.

**Comment by Reikion** [comment]
I'm not Mumble dev, but considering #4000, your best bet is to try to patch it by yourself and build package for macOS.

**Comment by Krzmbrzl** [comment]
I looked into this and the fix shouldn't be very intrusive. Therefore I'll added this issue to be fixed in the 1.3.1 release.

**Comment by Krzmbrzl** [comment]
Okay I need a guinea pig that is willing to test this out and report if the error is gone with my fix. I can't test this myself as I don't have a mac at hand.

You can download the installer of the snapshot from https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=1392&view=artifacts&type=publishedArtifacts

**Comment by Agraphie** [comment]
Thanks for your fix! I have a Mac and tested it. When launching the app normally it doesn launch. Through zsh I get the following error
```
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.22.dylib
  Referenced from: /Applications/Mumble.app/Contents/MacOS/Mumble
  Reason: image not found
```

The new dmg is also ~10 MB smaller than the 1.3.0 release. Is that expected?

**Comment by Krzmbrzl** [comment]
Uhm okay this seems to me as if normally the installer for macOS either automatically installs its dependencies alongside or that usually the Mac build uses static linkage for things like protobuf.

This would account for the smaller binary size.

Sadly this means though that i have absolutely no clue how to deliver a working installer to you. I was hoping that the one built on the CI is functional...

**Comment by Krzmbrzl** [comment]
@Agraphie could you try whether you can use the oinstaller from https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=1393&view=artifacts&type=publishedArtifacts please?
This is not the Overlay fix but a tweak I added for compiling Mumble. In theory that should resolve the error you encountered. If it does, I'll port the change to the Overlay fix so you should then be able to install and test it :)

PS: If you are faster than @Agraphie to test this is out, you are very welcome to do so and report the results :)

**Comment by migaspar** [comment]
@Krzmbrzl still not running, but missing SSL now:
```
Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/Mumble.app/Contents/MacOS/Mumble
  Reason: image not found
```
On macOS 10.15.3 there is /usr/local/opt/openssl/lib/libssl.1.1.dylib available.

**Comment by Krzmbrzl** [comment]
@migaspar thanks for the report.

Okay then I don't know how this should be done... Maybe someone else from the team knows something about this. I'll go and ask them
