### ISSUE TITLE
Mumble displays wrong information when retreiving information from SRV

### ISSUE THREAD

**Issue by IncredibleLaser** [mumble-voip/mumble#3563]
When you connect to a server using SRV, Mumble will display the wrong information about the server and, given a certain configuration, check for the wrong server certificate.

Example: My umurmur server runs on the server mydomain.com (I will gladly provide the real domain if needed) on the standard port 64738.

I have created the following SRV entry: _mumble._tcp.mumble with the port information and the target host mydomain.com. No A or AAAA entry exists for mumble.mydomain.com.

To test the setup, I create a new favorite with the following data: mumble.mydomain.com port 1. I can successfully connect to that server, showing that the SRV works. Two problems arise then though:

1. In the server information view, mumble will show server and port that you have entered in the favorites, e.g. "Remote host mumble.mydomain.com (port 1)" instead of the correct "Remote host mydomain.com (port 64738)".
2. Mumble will check for the server certificate for mumble.mydomain.com while what's actually needed is a certificate for mydomain.com. (can't test that right now because I have issued a subdomain certificate to have everything working for the moment)

**Comment by biolauri** [comment]
I totally agree with the first point. It would be really nice to change the port in the server settings to the one retrieved by the SRV record.

I also agree with Mumble trying to verify the server's certificate for the _wrong_ domain. I think, it'd be okay from a security perspective to verify against the domain in the SRV target as that's the counterpart of the connection. To check if the SRV Resource Record is correct, DNS integrity checks (like DNSSEC) would be best (see, for example, [some serverfault answer for SRV records and certificates](https://serverfault.com/a/862931/602095)).  
By the way, the current behaviour is documented in the [official docs about SRV records](https://wiki.mumble.info/wiki/SRV_Record#SSL_Certificates_and_SRV).

---

But I've got a solution for your specific use case: Why is your entry name (`_mumble._tcp.mumble`) for the `mumble` subdomain (`mumble.mydomain.com`)? Wouldn't it be easier to just use `_mumble._tcp.` as the entry name? Then your server address would be just `mydomain.com` and you wouldn't run into certificate problems.

I know, your issue is quite old, but maybe that'll some getting here having a similar problem.

**Comment by Krzmbrzl** [comment]
@IncredibleLaser @biolauri which version of Mumble are you using? 1.3.3 or older?

'cause it seems that this should have actually been fixed in 1.4.0 (unreleased yet - but you can get it by compiling the source code from the current master branch yourself or waiting for us to release a snapshot) via #3820

**Comment by IncredibleLaser** [comment]
Sorry for the late reply. I'm using 1.3.3 from my official repositories and the port issue is still present. It's also present on git master. However, this is only the case when I connect from favourites: using the command line, (mumble mumble://laser@mumble.mydomain.com) I get the correct port in server information.

Regarding the subdomain issue: it doesn't seem changed, but that might just be the new info not propagating due to TTL. I'll review that later and come back. I'll gladly provide more information later via on mumble itself.

**Comment by Krzmbrzl** [comment]
Okay good to know :+1: 
I am currently unable to look into this issue though (not enough time). But if there is someone who wants to tackle it, we'd appreciate it :point_up:
