### ISSUE TITLE
Make automatic lowering of game audio non-default

### ISSUE THREAD

**Issue by derlade** [mumble-voip/mumble#3781]
In my experience, every time I have asked new users to install Mumble for in-game voice communication, they report that the default lowering of game sound is very annoying, since it is enabled by default and you are thereby left wondering what is causing this effect, and it is especially annoying in highly competitive games, since it can be detrimental to have your in-game sound lowered in the wrong moment. I have yet to meet somebody who left this option enabled.

**Comment by Krzmbrzl** [comment]
It's certainly something the normal user won't expect. Thus making this disabled by default could make the user-experience more seamlessly.

And if someone actually wants that feature, he/she can head over to the options and turn it on

**Comment by Kissaki** [comment]
I strongly agree.

**Comment by davidebeatrici** [comment]
I agree, let's disable the option by default.

**Comment by trudnorx** [comment]
Agreed.

**Comment by trudnorx** [comment]
Wasn't this already discussed by #2711 and fixed by #2946?
Is the reporter of this bug using old version?

**Comment by derlade** [comment]
I don't know if this has been changed with 1.3.0, but with 1.2.19 it was a frequent occurrence that I had to explain to newcomers also installing 1.2.19 where this feature can be disabled.

**Comment by Kissaki** [comment]
@trudnorx Thank you for spotting that.

The referenced commit is from 2017, so between 1.2 and 1.3, and the value is still present currently. So this is indeed fixed in 1.3.0.

**Comment by Kissaki** [comment]
Duplicate of #2711
