### ISSUE TITLE
Debian 10 (Buster) backport 

### ISSUE THREAD

**Issue by streaps** [mumble-voip/mumble#4145]
The [Installing Mumble](https://wiki.mumble.info/wiki/Installing_Mumble#Debian) wiki page tells me that there should be a backport of Mumble 1.3.0 in Debian stable:

_Debian unstable has the latest release at all times in its repository. Backports to current stable are done as soon as the package reaches testing (usually a week after release)._ 

but there is only Mumble 1.3.0~git20190125.440b173 in stable. The 1.3.0 release is in testing since last year.

**Comment by toby63** [comment]
Probably @crknadle

**Comment by Krzmbrzl** [comment]
The package is not maintained by us. Thus I'd ask you to contact the respective package maintainer directly (however that works on Debian) :point_up:

**Comment by streaps** [comment]
Then it is a documentation bug and needs to be fixed in the wiki. Please reopen the issue until then.

**Comment by Krzmbrzl** [comment]
I just corrected it.

Note also that you can edit the wiki yourself. So if you see an error, you can correct it yourself :)

**Comment by toby63** [comment]
> I just corrected it.

Actually it is still not correct and history does not show a change:
> Backports to current stable are done as soon as the package reaches testing (usually a week after release).

This seems to not be the case (right now).

Also the wording is a little sketchy to be honest, because
"Backports to current stable" could mean two things:
1. Package gets included in stable (buster)
2. Package gets included in stable-backports (buster-backports)

Maybe you could reopen this and wait for an answer by @crknadle to clarify the situation?
Then we (maybe I) could change the wiki.

It is related to mumble and the mumble wiki.

**Comment by Krzmbrzl** [comment]
> Actually it is still not correct and history does not show a change:

It is corrected. We're having some caching issues with the wiki that leads to changes not being overtaken for everyone but the author of these changes for some time...

> Maybe you could reopen this and wait for an answer by @crknadle to clarify the situation?

What good would it do to have this issue open? The issue that concerns us directly was that the info on the wiki is outdated. This I have fixed. The other issue is not related to us in the sense that the Debian package is not maintained by us (The Mumble Team). Therefore the issue about that should be reported to Debian instead.

And if crknadle feels like it, he can still comment on this issue even if it is closed. And if this brings up something that feels like it should be on the wiki, it can be changed/added at any time :shrug:

**Comment by toby63** [comment]
Update on this:
I spoke to Mr. Kandle.
He told me that a different person used to do the backport-builds of mumble and that work on this was "dropped".
He also said that it is "possible but not likely" that a new build for the backports repo will be released.
In other words, someone else should do it, if they want it.

**Comment by streaps** [comment]
Thanks for the info.

The Debian way is such a waste of resources and frustrating for the user. It shouldn't be more work than changing the version, updating the build sources and push the button. Using a git snapshot of a version that hadn't been released (and no release candidate) and then not update the package for a very long time, is not even a conservative approach.

For my raspberry pi the options are:

- self compilation
- mixing repos (buster and testing)
- upgrading to testing
- switch to another distro
- continue to use the unsupported Mumble git snapshot

**Comment by toby63** [comment]
> It shouldn't be more work than changing the version, updating the build sources and push the button

Well while I agree that it could be easier (in a perfect world you would have a package manager that can manage all the things (including packages build from source; modifications etc.));
actually (I don't know how much you tried yet) sometimes one is lucky and it is not that much harder.
You can download the debian sources and modify them a bit, basically it's:
1. replace the src-folder with the recent sources.
1.a) create a .tar file from the original sources
2. modify the files in folder `debian`:
* `control` (dependencies) (not necessary if you are lucky, but can "easily" (because travis uses ubuntu) be read from the travis build config on mumble: https://github.com/mumble-voip/mumble/tree/master/scripts/travis-ci )
* `rules` (build options) (see above)
* `changelog` (necessary, `dch` is your friend) (only obstacle can be the numbering)
* `.install`-files (if new files or folders need to be placed somewhere) (mostly not necessary)
3. try to "rebuild" the package with:
`debuild -b -uc -us` (or similar)

In the case of 1.3.0 you might even just try to just use the debian sources from the 1.3.0 version and rebuild them on an older debian system (in a container for example).

For raspberry the situation is unknown to me, is it arm64?
I have nearly no knowledge about cross-builds.

**Comment by streaps** [comment]
Raspbian and my Pi 2 is still 32-bit. I don't know how hard or easy cross compilation for debian packages is. Maybe it possiblee use a github action? It should also build on the raspberry with some patience.

But it's a waste of time and energy, if users have to compile their own software, because the distribution ships outdated versions. I think I better spent my time in looking for a better distribution.

**Comment by toby63** [comment]
> But it's a waste of time and energy, if users have to compile their own software, because the distribution ships outdated versions. I think I better spent my time in looking for a better distribution.

Thats true.
For Desktops there are some good alternatives, but I don't know about Raspberry.
I always read about Debian-based distros for that.
