### ISSUE TITLE
Gap appears above each line of text

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5886]
### Description

1.4.287 addresses the text scaling issue but introduces a gap above each line of text

Relevant: https://github.com/mumble-voip/mumble/pull/5866

### Steps to reproduce

1. Look at the text pane

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![20220914](https://user-images.githubusercontent.com/56807288/190255449-1e8657f0-56db-449c-89d5-4a835c0841cc.png)

**Comment by Krzmbrzl** [comment]
Quoting from https://github.com/mumble-voip/mumble/pull/5820#issuecomment-1248150822
> I suspect the problem is with setting font sizes on windows. Qt docs say anything > 0 is valid, but I'm thinking that the windows implementation is more picky.
>
> [doc.qt.io/qt-5/qtextedit.html#setFontPointSize](https://doc.qt.io/qt-5/qtextedit.html#setFontPointSize)

Given that the function accepts a real number (instead of only integers) and Qt docs state

> Note that if s is zero or negative, the behavior of this function is not defined.

I think we should first attempt to pass `std::numeric_limits<qreal>::min()` - aka: the smallest possible value > 0 :thinking:

**Comment by Krzmbrzl** [comment]
Ah okay. Then I misunderstood. I was under the impression that we're currently passing `0` into the function. As it stands, my suggestion is of course nonsense.

**Comment by bkaestner** [comment]
@Krzmbrzl just to be sure, is this already fixed by #5820 or another PR on `master`? Otherwise I'd give it a shot (although I can only start working on it next Monday).

**Comment by Krzmbrzl** [comment]
No this is not yet fixed. We had other issues with the chat log that we have addressed in the latest release, which created the regression that is tracked in this issue. So we'd happily take any attempt at fixing this :+1:

**Comment by bkaestner** [comment]
Short update: I'm having some trouble with the `vcpkg` dependencies, apparently something about paths (e.g. `ctype.h` not found), at least when I run `scripts\vcpkg\get_mumble_dependencies.ps1`. I'll have to check tomorrow whether that still happens after a complete reinstall of the VS Build Tools and either file an issue here (or on `vcpkg`) or continue with this issue :)

**Comment by Krzmbrzl** [comment]
See also https://stackoverflow.com/q/42258311
