### ISSUE TITLE
Are there "central server" issues currently?

### ISSUE THREAD

**Issue by Scar1943** [mumble-voip/mumble#6954]
### The issue

Folks, for a few days now, I've noticed errors registering and retrieving central server data to clients and my murmur server. 

Are there ongoing issues that I'm not aware? Murmur and clients

![Image](https://github.com/user-attachments/assets/42004659-5bd5-402a-b9be-a07f1b7c7a3d)
![Image](https://github.com/user-attachments/assets/b11d83c3-ddd5-43f4-b3e2-dfeeec8ca7cc)

 are 1.5.735.

### Mumble version

1.5.735

### Mumble component

Server and Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Thanks for the report! We have upgraded our main server and this has caused quite a mess in the web server configuration. The problem should be resolved now. If not, please let me know

**Comment by Scar1943** [comment]
My last update request was at 1:02 EST and rejected. 

![Image](https://github.com/user-attachments/assets/55bd4f0c-5c0b-4c3a-9d6a-c3c771942d30)

**Comment by hamilton5** [comment]
just now: 

> 2025-10-15 15:42:38.351 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request

**Comment by winex** [comment]
i confirm broken registration, `mumble-server-1.4.287-8.fc42.x86_64`

some logs from the first failure at 13th of October, `UTC+3`:
```
<W>2025-10-13 11:45:13.996 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Internal Server Error
--- * x8 more times * ---
<W>2025-10-13 21:08:08.598 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-13 22:09:40.160 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
--- * x5 more times * ---
<W>2025-10-14 03:26:40.105 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-14 04:29:16.518 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
--- * xNN more times * ---
<W>2025-10-15 00:21:10.739 1 => Registration failed: Connection closed
<W>2025-10-15 01:21:36.396 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
<W>2025-10-15 02:23:41.763 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
<W>2025-10-15 03:26:07.100 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-15 04:28:58.915 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
--- * xNN more times * ---
<W>2025-10-15 18:54:16.126 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-15 19:57:32.769 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
--- * xNN more times to this very second :( * ---
```
_sorry for much logs, big wow_

hope that helps!

**Comment by Krzmbrzl** [comment]
Does anyone still experience the registration problem _now_? All provided logs seem to be of messages from a couple of days ago. Our services were (supposedly) fixed on Wednesday evening. Hence the question: does anyone get the error logged which is newer than today (now - the time I am writing this post)?

**Comment by winex** [comment]
> --- * xNN more times to this very second :( * ---

this is STILL happening, it's not couple of days old:
```
<W>2025-10-15 18:54:16.126 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-15 19:57:32.769 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
...
...
...
<W>2025-10-17 12:28:58.621 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
--- restarted server ---
<W>2025-10-17 13:13:18.328 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Bad Request
```

can it be some SSL issue or even DPI-blocking? i'd try other connection, but different IP won't succeed, of course

should i try to `tcpdump` connections FROM `publist-registration.mumble.info` to see if that works?

_p.s. just check Europe->Russian Federation list. yesterday it had like 4-5 servers only, but today it's a bit more populated, though iirc it should be about 20 or so_

**Comment by Scar1943** [comment]
> Does anyone still experience the registration problem _now_? All provided logs seem to be of messages from a couple of days ago. Our services were (supposedly) fixed on Wednesday evening. Hence the question: does anyone get the error logged which is newer than today (now - the time I am writing this post)?

Yes, as of 8:55 am EST 10-17, it's still happening. 

![Image](https://github.com/user-attachments/assets/137a02c8-3020-44bb-9b8d-687ebc7ac71f)

**Comment by hamilton5** [comment]
just looking at https://www.mumble.com/serverlist/  and only seeing 6 US servers is kind of a clue to me.

and yes as of about a half hour was my last check, and it failed.

**Comment by winex** [comment]
@hamilton5 oh, there is public a list, of course :)

@Krzmbrzl i hope you guys didn't force reverse-ip check (PTR, `*.in-addr.arpa`), so that only **real static IPs** (dedicated servers) are allowed...
_because my IP doesn't point to my domain, and my ISP will probably never allow me to change that_

**Comment by Hartmnt** [comment]
We are still investigating the problem. We did not change any registration logic, but we updated our infrastructure operating system and software. Something is still not working right, but what makes it hard is that it seems to flap between working and not working on our end.

**Comment by Scar1943** [comment]
Ok, looks like it was successful at 11:26 10-17 today. First in quite some time. :-)

I'll watch it throughout the day to see that it keeps going. 

![Image](https://github.com/user-attachments/assets/49c2c711-76d8-404e-b740-a3d3176d0dfb)

**Comment by hamilton5** [comment]
> Ok, looks like it was successful at 11:26 10-17 today. First in quite some time. :-)
> 
> I'll watch it throughout the day to see that it keeps going.
> 
> ![Image](https://github.com/user-attachments/assets/49c2c711-76d8-404e-b740-a3d3176d0dfb)

I also had 1 good one, but didn't want to speak to soon. I'm glad I didn't the next one failed for me. Was going to hold off until they confirm it's fixed.

**Comment by Krzmbrzl** [comment]
The issue should be fixed now (hopefully for real this time!)

**Comment by winex** [comment]
thank you, guys! i'll try to keep you informed if anything goes wrong!

```
<W>2025-10-17 18:22:18.990 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
<W>2025-10-17 19:24:46.888 1 => Registration: Attempting to connect to <IP:PORT>...
Registration updated!
```
_`UTC+3`_

**Comment by hamilton5** [comment]
So far so good for me, US servers seem back to normal. Could this issue still be affecting other regions? I recall a lot more China servers, Brazil only has 1 now currently too. Do you have public server history from before the 13th you can compare to today?

**Comment by Scar1943** [comment]
Successful seems pretty regular now. 4:56pm EST.

**Comment by Krzmbrzl** [comment]
> Do you have public server history from before the 13th you can compare to today?

We don't
