### ISSUE TITLE
Strange Opus audio bug affecting at least 2 of our users.

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#957]
This has been an ongoing problem with at least 2 of our users ever sense Opus was implemented. Our workaround is to force the server to use Celt though the overall sound is not near as good.

The server is Arch Linux 64 running the latest git snapshots and this problem still exists as of Feb 10 2013. 

The clients are all Windows running current snapshots. 

User 1: The most frequently affected has used multiple different MICs, headsets and has recently had to switch MOBO and CPU due to a recent MOBO failure. Sadly this didn't fix the problem. The problem also persists between windows 7 and 8. Next time he is in Linux I will test if he still has the problem. I'm attaching his dxdiag and an audio sample.

User 2: Affected far less often. Has nearly the same hardware as I. The only notable difference is he is running 3 AMD GPUs vs my one Nvidia GPU.  He has recently switched from an M-Audio Producer USB Mic to a Logitech G930 and still the problem persists. 

User 3: Me, not affected at all, other than the ear shattering pain... Only other notable differences from User 2 I can think of is I'm using a Killer 2100 Nic “Don't judge me I got it for free.” and i'm using a Blue Yeti MIC. I haven't had this problem in windows 7 8, Arch Linux 64 and FreeBSD 9.1.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/957/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/957/attachment/User3.DxDiag.txt*

**Comment by petercrabtree** [comment]
The best workaround is to disable Opus. It sucks, but at least your ears will stop bleeding.

**Comment by Atrixium** [comment]
How do you disable Opus, I can't seem to find any reference for it?

**Comment by jzelinskie** [comment]
@Atrixium http://wiki.mumble.info/wiki/Murmur.ini#opusthreshold
If you set this value over 100, it can never be reached, thus the server will always use CELT.

**Comment by n0rc** [comment]
@jzelinskie 
Thanks, this works for me. Hopefully that bug in Opus will get fixed soon.

**Comment by shulima** [comment]
Really glad to see there at least is a workaround. After the last bug-induced screech on mumble, my ear is actually hurting.

**Comment by wrycu** [comment]
Has a root cause been identified?  Are there any planned fixes? I'm glad to see there's a workaround, but not so glad to see we have to lose voice quality for it.

**Comment by mgalvey** [comment]
Is there anything we can do to narrow down the cause of this? I'd be willing to run a debug build of Mumble (and have the users on my server "causing" the problem do the same) to try and determine what causes this.

**Comment by KappaNitori** [comment]
This issue has been plaguing my server for a while now, and it seems to be getting worse. It follows me the most- other users occasionally transmit a pop or quick beep at the front of a transmission, but apparently my client is sending out long screeches that sound just like the attached audio samples that have been posted earlier in this thread. Found this thread, tried disabling noise suppression, no luck. We're all running push to talk, and since I rent the server through mumble.com, their UI won't let me set the opus threshold over 100. (Can anyone think of another workaround in the meantime?)

If this helps at all, long ago before this screeching problem started but after the 1.2.4 release, some of our users found out how to intermittently induce a strange audio artifact. By disconnecting and reconnecting to the server while holding the push to talk key and speaking right as the connection is made, sometimes the transmission would get a strange burst of reverberation, making the transmitted voice sound like the fictional "Geth" character Legion from the Mass Effect series, or like shouting into a PVC tube- some of our users found it quite amusing but it was never a 100% certain occurrence. Potentially unrelated, but I figured it bears mentioning.

**Comment by avatias0** [comment]
can confirm it is screech-tastic. tested with mumble-server hosted on both debian and windows
Started off only affecting certain users but now everyone is having a screech. Trying the workaround, hope it works

**Comment by LaikeSF** [comment]
Our server is having similar issues, we actually stopped running Mumble for a while because of it. We decided to give the 1.3.0 snapshot a try today and we encountered the screeching bug a few hours into use. Not sure how we can help, but we'd love to go back to OPUS as soon as it's fixed. In the mean time, we've switched back to CELT.

**Comment by KappaNitori** [comment]
Didn't want to post anything until I had time enough time to test this, but I've found a non-CELT workaround. It's been working for a few weeks now, no screeches where they had previously occurred almost hourly.

It's something to do with the compression quality settings. I set mine to the highest quality available (96.0kb/s) and the lowest audio per packet (10 ms) - this greatly increases the bandwidth needed, but apparently fixes the screech. Noise suppression is off as well.

**Comment by LaikeSF** [comment]
I can give this a try. Is there some way to force these settings on all clients? Or will I have to instruct all incoming users to change their settings?

**Comment by Natenom** [comment]
We have good experience with just disabling the "Max. amplification" in "Audio Input". I produced the bug very often and since the change it didin't occur anymore.

**Comment by pilot51** [comment]
I've been on the receiving end of this issue for a while. I had been suggesting, on a hunch, that max amplification be set no higher than 2 (where I have it set). It seemed to be doing the trick, but then as I was directing someone with the screech to lower it, he said it was already set to 2, so I asked him to set it to 1 and it seems to be working fine after about an hour, then I proceeded to look more into the issue and ended up here.

Most of the people I talk with are on Windows 7 or 10, while I'm on Linux Mint 17.2 and a couple friends dual-boot Windows with Mint or Ubuntu. All clients have OPUS support. I've confirmed that two of the people with the issue are on Windows 10, one with 1.2.10 and USB mic, one with 1.2.9 and audio jack mic. There were a few others affected in recent months, but I didn't get the details. I'll pay more attention when it inevitably happens in the future.

**Comment by monestri** [comment]
This should be a high priority bug as it impacts the core functionality of the software. I can say that mumble with screeching is not very usable.

**Comment by dstensnes** [comment]
+1

This is very annoying. Scares the crap out of me if noone has said anything in a while, and this kicks in...

**Comment by roothorick** [comment]
We seriously need to work on reproduction steps here. "Me too"s don't help anyone; there's a subscribe button to the right if you just want to be notified of developments.

Important observations:

* The problem occurs for only a fraction of a second, at the very beginning of a transmission
* Disabling amplification seems to prevent the issue from occurring

The most obvious possibility is that the Opus encoder somehow makes Mumble's internal amplification "lag" in terms of setting an appropriate gain. If so, a few ms of near-silence followed by relatively loud voice, with just the right timing, may possibly be a reliable trigger.

A previous post mentioned that setting audio per packet to 10ms solved the issue for them. I observed that myself and another user not exhibiting the issue already had it set to 10ms. The problem user was set to 30 instead. We pulled him down to 10 as a test. Maybe the amplifier is only considering a fixed length of audio, instead of the whole packet? Then I wonder why it would only be Opus and not other codecs as well...

**Comment by mkrautz** [comment]
We would like it if people could try out the latest snapshot available on mumble.info.

Version 1.3.0~883~g2a31708~snapshot.

This snapshot includes the commit 23fa9b3979c244f1bcdbc80972a88ef7144f8f4a, which we believe could be related to this issue.

Thank you.

**Comment by frymaster** [comment]
For what it's worth no one has complained about me glitching their eardrums since this update.  One of the other main culprits (who, now I think about it, has a really poor quality connection and I may have suggested he increase his audio-per-packet to compensate) hasn't been around much, but I'll encourage him to use the snapshots and see what happens

**Comment by mkrautz** [comment]
FWIW, the aforementioned commit has now been cherry-picked into 1.2.12, which was released just now.

We hope the bug was fixed by the commit, but we are still not sure.

Thanks.

**Comment by dazoe** [comment]
So we just tried out the latest release.. soon I lowered my audio per packet to the lowest setting which is 20 ms if I remember correctly my buddy screamed 'OUCH, it's not fixed'...
```
Server info
Version: 1.2.12
OS: Archlinux (freshly updated)
```

**Comment by RED-404** [comment]
Yeah, I'm the one who screamed 'OUCH, it's not fixed'...
Dazoe was running client version 1.2.12
I was running client version 1.3.0~895~gfe81316~snapshot.
We both had APP set to 10 ms and Echo Cancellation enabled
Murmur had never been installed on this server and its configuration was basically still default. Nothing that didnt need to be changed was changed.

Server info
OS: Arch Linux x86_64
Hostname: eligos
Kernel Release: 4.2.5-1-ARCH
Uptime: 40 days, 2:16
WM: None
DE: None
Packages: 375
RAM: 2281 MB / 7988 MB
Processor Type: Intel(R) Xeon(R) CPU           L5420  @ 2.50GHz
Root: 98G / 472G (20%) (ext4)
Murmur Version: 1.2.12

dxdiag for my system. "Probably of no help"
[Red-DxDiag.txt](https://github.com/mumble-voip/mumble/files/72328/Red-DxDiag.txt)

**Comment by hacst** [comment]
Interesting. The issue we fixed - afaik - shouldn't occur at 10ms pp latency. Maybe this is something else. Was really hoping the whole issue would be solved by the fix :(

**Comment by roothorick** [comment]
Setting APP to 10ms proved to be a functional workaround for us (and was what we wanted to use anyway) which makes me think there's two issues here, and you fixed one of them. But I haven't exactly looked at the code or anything.

**Comment by frymaster** [comment]
People are saying I made those kinds of noises the other night.  But I think the incidence of these has been *drastically* reduced, so I think it's highly likely **a** source of this has been fixed

**Comment by druni** [comment]
Still not fixed, so far i've only heard it from users with "unstable internet", basicly when they get a lagspike you will hear this "horror scream bug"

**Comment by dazoe** [comment]
@druni, I'm not sure if internet connection plays a role. My server and I
have very stable internet connections. I'm very picky when it comes to
packet loss and ping jitter. I almost always have 2 ping plotters running
watching my connection to the server as well as another server in a
different region.
Me and another guy (with the same ISP and I) are "causing" this we don't
really have anything in common except for using similar AMD processors
(FX-8xxx)
A third person with very poor connection (Rural Wireless) never "causes"
the problem.
So far we haven't been able to come up with a work around. changing the
audio per packet to 10ms seems to lower the frequency of the problem but it
doesn't stop it.
We have since moved away from mumble sadly. But every once in a while we
install a server and give it a go. In the years that mumble has had this
bug it seems to have gotten worse. I remember when it first started it only
happened something like 2 or 3 times a day. (We spend a lot time in VOIP
apps)
The last time we tried it the issue came up right away.


On Sun, Feb 7, 2016 at 1:32 PM, druni <notifications@github.com> wrote:

> Still not fixed, so far i've only heard it from users with "unstable
> internet", basicly when they get a lagspike you will hear this "horror
> scream bug"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumble-voip/mumble/issues/957#issuecomment-181090574>.
>



-- 
-Dave

**Comment by DGMurdockIII** [comment]
I still hear it

**Comment by mkrautz** [comment]
@DGMurdockIII Was this with people using new-ish clients only? The problem will be at the sender-side, so even if you have updated, everyone else will need to, too. (1.2.9 and 1.3.0 snapshots should have the fix for one of these issues, at least.)

**Comment by Kissaki** [comment]
My friend had sound artefacts on beginning to transmit audio relatively often. Since he upgraded/changed his PC they no longer occur. He had quite and old client for a long time (1.2.4), but IIRC I asked him to update some time ago - but I'm not sure if he did. Anyway, with the new PC, as he downloaded Mumble, he has a newer version and no more artefacts.

**Comment by Abextm** [comment]
I'm not sure the issue is sender side. I have a custom mumble [client/bot](bitbucket.org/abex/yumeko). It uses libopus1.2a to decode the packets, which are then piped into ffmpeg to encode them. [Source](https://bitbucket.org/Abex/yumeko/src/1341a3fe6533313f578231651d14ad3f9e308f55/mod_recorder.go?at=master&fileviewer=file-view-default). Server is running a modified ~1.5 year old 1.3 beta on CentOS7x64. Sending client was 1.3.0~19xx an Win10-1607x64 and I believe the receiving clients that heard the screech were the same version/OS. The bot is on the same machine as the server.

**Comment by Abextm** [comment]
Actually I only use libopus1.2a my development environment. On the server it actually uses opus 1.0.2-6.el7.

**Comment by Abextm** [comment]
I have more data, now in the form of opus data. You can find the opus [here](https://github.com/mumble-voip/mumble/files/1015951/bad.noises.raw.zip). The bad noises supposedly happen at about 43 seconds in, but as you can tell this is not recorded. The recorder does not modify the opus data in any way, however it does discard metadata, such as sequence number and position.

**Comment by Abextm** [comment]
I wrote a quick client with gumble to replay the opus data. It didn't trigger the bug. This narrows the problem down to something with metadata or timing (probably). I doubt its a timing bug because it always (at least for my users) triggers for everybody at once, and I doubt a timing issue could be propagated so reliably over our varying connections.

**Comment by mkrautz** [comment]
@Abextm My comment about it being sender-side was because we fixed a bug a while ago (and backported it to 1.2.x), which could cause a similar screech: https://github.com/mumble-voip/mumble/commit/23fa9b3979c244f1bcdbc80972a88ef7144f8f4a

So if some people on the server were on a version that does not contain the fix, those people could produce a noise that would be heard by everyone else on the server. (That is, one person with an old client could ruin it for everyone else, because the noise is produced in AudioInput.)

**Comment by mkrautz** [comment]
@Abextm Thanks for working on this, BTW!

**Comment by mkrautz** [comment]
BTW, was the speaker in the recording using VAD, Continuous, or PTT?

**Comment by Abextm** [comment]
Excluding the bot, everyone was on Mumble 1.3.0\~2389\~gdde8173, using Voice activity.

**Comment by DGMurdockIII** [comment]
Nice if this gets fixed Voice activity might be actually OK to use then if set up right

**Comment by oppa1** [comment]
About a month ago I enabled Opus again. We had screeches, but one of my visitors was using an old version of Mumble, I can't recount but I think it was around 1.2.10. I told him to upgrade to 1.2.19 and since then we haven't encountered the screeching bug. 

Everyone is using Voice Activity and the (Murmur) server version is 1.2.19 on Alpine Linux. It's fixed for us, so thank you!

**Comment by avatias0** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "oppa1 [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCWEIGCENDAMYRBQLKAFYZCAWBHGJDUBBRW3BAPCGMYASAG5QSDWFXGAY4CAFJAUFKOKIPFYAF4HDBD2WBQIVEGAYHRA4RQ5ATRWNEHMRURAOUFB6INTEACCKDIFAQHIILGEELCALRACYQS46AXLAB7QAXYAGJEVKTWMIUSAABA@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Tue, 20 Jun 2017 15:45:41 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  elliot@esay.es
    Unrouteable address

**Comment by davidebeatrici** [comment]
We have updated Opus to version 1.2.1.

Could you check if the issue still appears with the latest snapshot (**1.3.0~2458~g176c041~snapshot**)?

**Comment by avatias0** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Davide Beatrici [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCWEIGCENDAMYRBVRAD2ABYGYBTAGOAEUABAJQFCXIEADJRAOKK3E43MIEFIQSHEADMMMOSGLZQF3ST3KDIQAR3ATT4KFAS6IRJONE6SVHRAOSF63YX2MACCKDIFAQHIILGEELCALRACYQS46AWRAB7QAXYAGIXEFRRYYREACFAAAQA====@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Thu, 06 Jul 2017 17:23:52 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  elliot@esay.es
    Unrouteable address

**Comment by davidebeatrici** [comment]
I have deleted these two comments because they are failed delivery mails sent from Junk Email Filter, because avatias0's email address isn't available anymore and he is subscribed to this issue.

Every time somebody posts a comment (such as this one), a new one from avatias0 appears. Sadly there is nothing we can do.
Let's hope this issue is solved, otherwise I propose to move the discussion to a new issue.

**Comment by davidebeatrici** [comment]
I'm assuming this is not an issue anymore.

**Comment by Abextm** [comment]
Nope still happens, and I still can repro it in any way

**Comment by davidebeatrici** [comment]
@Abextm Does it still happen?

**Comment by Abextm** [comment]
Server is on a slightly modified f2cbebd 

There are clients connected that use old versions of gumble, however these clients never have sent audio that causes the bug, and if they receive audio where other clients would hear the bug they are able to decode it without the bug. [source](https://bitbucket.org/Abex/yumeko/src/64266cceefa3c4d48f65803e0a6561de646dc538/mod_recorder.go?at=master&fileviewer=file-view-default)
When the bug does occur all of the normal mumble clients hear it simultaneously 

Here are some versions that have been connected to the server recently. The bug only happens about once a month anymore, so I can't provide any more specifics on which clients are connected.

 - `1.3.0~2729~g2126495~snapshot`
 - `1.3.0~2586~g894ade2~snapshot`

**Comment by Krzmbrzl** [comment]
Is this still a thing?
